esphome:
  name: closet-led
  friendly_name: Closet LED

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

# switch:
#   - platform: gpio
#     inverted: true
#     pin: GPIO15
#     name: "on board LED"

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO0
    num_leds: 196
    rmt_channel: 0
    chipset: ws2812
    name: LED Strip

# logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: "abc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 10.69.69.204

captive_portal:

web_server:
  port: 80
