esphome:
  name: peephole-camera
  friendly_name: Peephole Camera
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue
    board_build.f_cpu: 200000000L
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

psram:
  mode: octal # octal (OPI) or quad (QSPI)
  speed: 80MHz

# Taken from
# https://wiki.seeedstudio.com/XIAO_ESP32S3_esphome/#1-add-seeed-studio-xiao-esp32s3-sense-to-esphome.
esp32_camera:
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13

  # Image settings
  name: Camera
  icon: mdi:camera

  resolution: 800x600
  max_framerate: 30 fps
  idle_framerate: 1 fps

  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false

  # Exposure
  aec_mode: manual
  aec_value: 300

  # Gain Control
  agc_mode: manual
  agc_value: 2

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: "abc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

captive_portal:

web_server:
  port: 80
